spring:
  profiles:
    include: oauth
  main:
    banner-mode: off

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
    show-sql: true
    open-in-view: false

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_LOWER=TRUE;MODE=MySQL;;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    driver-class-name: org.h2.Driver

server:
  servlet:
    encoding:
      force: true
